import { PLAYER } from './playerConstants';

export const GAME_BOARD_INITIAL_STATE = [
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.ONE, PLAYER.TWO, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.TWO, PLAYER.ONE, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
    [PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER, PLAYER.INVALID_PLAYER],
];
